export const FETCH_CHANNEL_DATA = 'FETCH_CHANNEL_DATA';
export const FETCH_CHANNEL_DATA_SUCCESS = 'FETCH_CHANNEL_DATA_SUCCESS';
export const FETCH_CHANNEL_HAS_ERROR = 'FETCH_CHANNEL_HAS_ERROR';
export const FETCH_CHANNEL_IS_LOADING = 'FETCH_CHANNEL_IS_LOADING';
export const FETCH_CHANNEL_ITEM_DATA = 'FETCH_CHANNEL_ITEM_DATA';

